## Transformacion de variables
Nombres: Mario Reinoso y Domenica Beltrán

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, StandardScaler


print('Librerias listas')

Librerias listas

In [5]:
df = pd.read_csv("AC2.csv", encoding='cp1252', sep=';')
df.head(10)

  sexo  edad     país nivelSatisfaccion
0    F    65   Brasil          me gusta
1    M    26   España       no me gusta
2    F    21    Chile           neutral
3    M    12  Ecuador       no me gusta
4    F    32   España          me gusta
5    M     9  Ecuador       no me gusta

In [4]:
df['NIVEL SATISFACCION'] = df['nivelSatisfaccion'].map({'me gusta': 0, 'no me gusta': 2, 'neutral': 1})
df = pd.get_dummies(df, columns=['sexo', 'país'], prefix=['SEXO', 'PAIS'], dtype=int)
df.columns = df.columns.str.upper()

columnas_ordenadas = [
    'SEXO_M', 'SEXO_F', 'EDAD', 
    'PAIS_BRASIL', 'PAIS_ESPAÑA', 'PAIS_CHILE', 'PAIS_ECUADOR', 
    'NIVEL SATISFACCION'
]
df_transformado = df[columnas_ordenadas]
df_transformado.head(10)

,SEXO_M,SEXO_F,EDAD,PAIS_BRASIL,PAIS_ESPAÑA,PAIS_CHILE,PAIS_ECUADOR,NIVEL SATISFACCION
0,0,1,65,1,0,0,0,0
1,1,0,26,0,1,0,0,2
2,0,1,21,0,0,1,0,1
3,1,0,12,0,0,0,1,2
4,0,1,32,0,1,0,0,0
5,1,0,9,0,0,0,1,2

In [19]:
promedios = df_transformado.mean()
desviaciones = df_transformado.std()

print("Promedios:")
print(promedios)
print("\nDesviación Estándar:")
print(desviaciones)

Promedios:
SEXO_M                 0.500000
SEXO_F                 0.500000
EDAD                  27.500000
PAIS_BRASIL            0.166667
PAIS_ESPAÑA            0.333333
PAIS_CHILE             0.166667
PAIS_ECUADOR           0.333333
NIVEL SATISFACCION     1.166667
dtype: float64

Desviación Estándar:
SEXO_M                 0.547723
SEXO_F                 0.547723
EDAD                  20.265735
PAIS_BRASIL            0.408248
PAIS_ESPAÑA            0.516398
PAIS_CHILE             0.408248
PAIS_ECUADOR           0.516398
NIVEL SATISFACCION     0.983192
dtype: float64

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_estandarizado = pd.DataFrame(scaler.fit_transform(df_transformado), columns=df_transformado.columns)

df_estandarizado.head(10)

,SEXO_M,SEXO_F,EDAD,PAIS_BRASIL,PAIS_ESPAÑA,PAIS_CHILE,PAIS_ECUADOR,NIVEL SATISFACCION
0,-1.0,1.0,2.027027,2.236068,-0.707107,-0.447214,-0.707107,-1.299867
1,1.0,-1.0,-0.081081,-0.447214,1.414214,-0.447214,-0.707107,0.928477
2,-1.0,1.0,-0.351351,-0.447214,-0.707107,2.236068,-0.707107,-0.185695
3,1.0,-1.0,-0.837838,-0.447214,-0.707107,-0.447214,1.414214,0.928477
4,-1.0,1.0,0.243243,-0.447214,1.414214,-0.447214,-0.707107,-1.299867
5,1.0,-1.0,-1.000000,-0.447214,-0.707107,-0.447214,1.414214,0.928477